module.exports.TIME_OUT_WAIT_ELEMENT = 40000;
module.exports.TIME_OUT_WAIT_ELEMENT_MIN = 5000;
module.exports.TIME_OUT_WAIT_ELEMENT_MED = 90000;
module.exports.TIME_OUT_WAIT_ELEMENT_MAX = 180000;
module.exports.TIME_OUT_WAIT_ELEMENT_DISAPPEAR = 10000;